spring:
  application:
    name: api-gateway
server:
  port: 5555

# route to url
zuul:
  routes:
    api:
      path: /api-gateway/**
      serviceId: compute-service
#    api-a:
#      path: /api-a/**
#      serviceId: compute-service
#    api-b:
#      path: /api-b/**
#      serviceId: compute-service-2
eureka:
  client:
    serviceUrl.defaultZone: http://localhost:1111/eureka/

